openapi: 3.0.1
info:
  title: A beer fridge service
  description: Beer fridge service build with openapi-generator
  version: 1.0.0
servers:
  - url: /
paths:
  /beers:
    get:
      tags:
        - beers
      operationId: getAllBeers
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            format: int32
            default: 20
      responses:
        200:
          description: list the beer operations
          content:
            application/io.grohm.go-workshop.beer-fridge.v1+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/beer'
    post:
      tags:
        - beers
      operationId: addOne
      requestBody:
        content:
          application/io.grohm.go-workshop.beer-fridge.v1+json:
            schema:
              $ref: '#/components/schemas/beer'
        required: false
      responses:
        201:
          description: Created
          content:
            application/io.grohm.go-workshop.beer-fridge.v1+json:
              schema:
                $ref: '#/components/schemas/beer'
        default:
          description: error
          content:
            application/io.grohm.go-workshop.beer-fridge.v1+json:
              schema:
                $ref: '#/components/schemas/error'
      x-codegen-request-body-name: body
  /beers/{id}:
    delete:
      tags:
        - beers
      operationId: destroyOne
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        204:
          description: Deleted
          content: {}
        default:
          description: error
          content:
            application/io.grohm.go-workshop.beer-fridge.v1+json:
              schema:
                $ref: '#/components/schemas/error'
  /temperature:
    get:
      tags:
        - fridge
      operationId: getTemperature
      responses:
        200:
          description: return the current fridge temperature
          content:
            application/io.grohm.go-workshop.beer-fridge.v1+json:
              schema:
                $ref: '#/components/schemas/temperature'
components:
  schemas:
    beer:
      required:
        - origin
        - title
        - volume-percentage
      type: object
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        title:
          minLength: 1
          type: string
        origin:
          minLength: 1
          type: string
        volume-percentage:
          type: number
          format: float
    temperature:
      type: integer
      format: int64
    error:
      required:
        - message
      type: object
      properties:
        code:
          type: integer
          format: int64
        message:
          type: string